//! CodeGen — emit Python transpiler output from an inferred Program.
//! Target: Python 3.10+ with type annotations and runtime assertion guards.
//! (LLVM IR stub is provided at the end for future native target.)

use std::fmt::Write;
use crate::ast::*;
use crate::constants::*;
use crate::kappa_infer::KappaInfer;
use crate::error::VesselResult;

pub struct CodeGen<'a> {
    program: &'a Program,
    ki:      &'a KappaInfer,
    out:     String,
    indent:  usize,
}

impl<'a> CodeGen<'a> {
    pub fn new(program: &'a Program, ki: &'a KappaInfer) -> Self {
        Self { program, ki, out: String::new(), indent: 0 }
    }

    pub fn emit(mut self) -> VesselResult<String> {
        self.emit_header();
        self.emit_vessels();
        self.emit_couples();
        self.emit_laws();
        self.emit_fns();
        self.emit_phi_rebalance();
        Ok(self.out)
    }

    // ------------------------------------------------------------------ header

    fn emit_header(&mut self) {
        self.line("# Generated by vesselc — Vessel Language Compiler");
        self.line("# Do not edit manually.");
        self.line("from __future__ import annotations");
        self.line("import math");
        self.line("from dataclasses import dataclass, field");
        self.line("from typing import Optional");
        self.line("");
        self.line(&format!("FORBIDDEN_LOW  = {FORBIDDEN_LOW:.10}"));
        self.line(&format!("FORBIDDEN_HIGH = {FORBIDDEN_HIGH:.10}"));
        self.line(&format!("TH1_TOL        = {TH1_TOL:.10}"));
        self.line(&format!("PHI_TOL        = {PHI_TOL:.10}"));
        self.line(&format!("MAX_REBALANCE  = {MAX_REBALANCE}"));
        self.line("");
        self.line("# --- Runtime support -----------------------------------------------");
        self.line("def _check_kappa(name: str, v: float) -> float:");
        self.indent();
        self.line("\"\"\"Guard: reject forbidden zone for non-sentient vessels.\"\"\"");
        self.line("assert v < FORBIDDEN_LOW or v > FORBIDDEN_HIGH, \\");
        self.indent();
        self.line(&format!(
            "f\"Vessel {{name}}: kappa={{v:.6f}} in forbidden zone ({FORBIDDEN_LOW:.4}, {FORBIDDEN_HIGH:.4})\""
        ));
        self.dedent();
        self.line("return v");
        self.dedent();
        self.line("");
        self.line("def _th1(kappa: float) -> float:");
        self.indent();
        self.line("\"\"\"T-H1: alpha = ln(kappa).\"\"\"");
        self.line("return math.log(kappa)");
        self.dedent();
        self.line("");
    }

    // ------------------------------------------------------------------ vessels

    fn emit_vessels(&mut self) {
        self.line("# --- Vessel declarations -------------------------------------------");
        self.line("@dataclass");
        self.line("class VesselNetwork:");
        self.indent();
        // fields
        for vd in &self.program.vessels {
            let inf = self.ki.vessels.get(&vd.name);
            let klo = inf.map(|i| i.kappa.lo).unwrap_or(0.0);
            let khi = inf.map(|i| i.kappa.hi).unwrap_or(1.0);
            let sentient = if vd.sentient { "True" } else { "False" };
            self.line(&format!(
                "# {} | kappa range: [{:.4}, {:.4}] | sentient: {}",
                vd.name, klo, khi, sentient
            ));
            // emit kappa literal as default field value
            let kv = expr_to_python(&vd.kappa);
            let bv = expr_to_python(&vd.boundary);
            self.line(&format!("{}_kappa:    float = {}", vd.name, kv));
            self.line(&format!("{}_boundary: float = {}", vd.name, bv));
            self.line(&format!("{}_alpha:    float = field(init=False)", vd.name));
            if vd.sentient {
                self.line(&format!("{}_sentient: bool  = True", vd.name));
            }
            self.line("");
        }

        // __post_init__
        self.line("def __post_init__(self) -> None:");
        self.indent();
        for vd in &self.program.vessels {
            if !vd.sentient {
                self.line(&format!(
                    "_check_kappa({:?}, self.{}_kappa)",
                    vd.name, vd.name
                ));
            }
            self.line(&format!(
                "self.{0}_alpha = _th1(self.{0}_kappa)",
                vd.name
            ));
        }
        self.dedent(); // __post_init__
        self.dedent(); // class
        self.line("");
    }

    // ------------------------------------------------------------------ couples

    fn emit_couples(&mut self) {
        if self.program.couples.is_empty() { return; }
        self.line("# --- Coupling registry ---------------------------------------------");
        self.line("COUPLES: list[tuple[str, str, float]] = [");
        self.indent();
        for cd in &self.program.couples {
            let cval = expr_to_python(&cd.coupling);
            self.line(&format!("({:?}, {:?}, {}),", cd.src, cd.dst, cval));
        }
        self.dedent();
        self.line("]");
        self.line("");
    }

    // ------------------------------------------------------------------ laws

    fn emit_laws(&mut self) {
        if self.program.laws.is_empty() { return; }
        self.line("# --- Law assertions ------------------------------------------------");
        for ld in &self.program.laws {
            self.line(&format!("def law_{}(network: VesselNetwork) -> bool:", ld.name));
            self.indent();
            self.line(&format!("\"\"\"Law: forall {}: {}\"\"\"", ld.param, expr_doc(&ld.body)));
            // Emit a check over all vessels
            self.line("results = []");
            for vd in &self.program.vessels {
                let body_py = emit_law_body_for_vessel(&ld.body, &ld.param, &vd.name);
                self.line(&format!("results.append({body_py})"));
            }
            self.line("return all(results)");
            self.dedent();
            self.line("");
        }
    }

    // ------------------------------------------------------------------ fns

    fn emit_fns(&mut self) {
        if self.program.fns.is_empty() { return; }
        self.line("# --- Function definitions ------------------------------------------");
        for fd in &self.program.fns {
            let fi = self.ki.fns.get(&fd.name);

            // build signature — no inline comments, annotations go in docstring
            let params: Vec<String> = fd.params.iter().map(|(p, _hint)| {
                format!("{p}: float")
            }).collect();
            let sig = if params.is_empty() {
                "network: VesselNetwork".to_string()
            } else {
                format!("network: VesselNetwork, {}", params.join(", "))
            };
            self.line(&format!("def {}({sig}) -> float:", fd.name));
            self.indent();

            // docstring with R7 annotations
            let mut doc = format!("Function '{}'.\n", fd.name);
            for (p, hint) in &fd.params {
                if let Some(h) = hint {
                    doc.push_str(&format!("  Param {p}: kappa in [{:.4},{:.4}]\n", h.lo, h.hi));
                }
            }
            if let Some(fi) = fi {
                doc.push_str(&format!("  Return kappa in [{:.4},{:.4}]\n", fi.ret.lo, fi.ret.hi));
            }
            self.line(&format!("\"\"\"{}\"\"\"", doc.trim()));

            // R7 param assertions
            for (p, hint) in &fd.params {
                if let Some(h) = hint {
                    self.line(&format!(
                        "assert {h_lo:.4} <= {p} <= {h_hi:.4}, \\",
                        h_lo = h.lo, h_hi = h.hi
                    ));
                    self.indent();
                    self.line(&format!(
                        "f\"R7 violation: param '{p}' = {{{p}:.4f}} outside [{h_lo:.4},{h_hi:.4}]\"",
                        h_lo = h.lo, h_hi = h.hi
                    ));
                    self.dedent();
                }
            }

            // body statements
            if fd.body.is_empty() {
                self.line("return 0.0  # stub: no body");
            } else {
                for stmt in &fd.body {
                    self.emit_stmt(stmt);
                }
            }

            // R8 return range check (appended after last statement if it was a return)
            if let Some(fi) = fi {
                if fi.ret != KappaRange::full() {
                    // The return value is named `_ret` when we can wrap it
                    // Here we emit a note; full wrapping requires SSA — left as inline comment
                    self.line(&format!(
                        "# R8: return kappa expected in [{:.4},{:.4}]",
                        fi.ret.lo, fi.ret.hi
                    ));
                }
            }

            self.dedent();
            self.line("");
        }
    }

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Let { name, value, .. } => {
                self.line(&format!("{name} = {}", expr_to_python(value)));
            }
            Stmt::Return { value, .. } => {
                self.line(&format!("return {}", expr_to_python(value)));
            }
            Stmt::Expr { value, .. } => {
                self.line(&expr_to_python(value));
            }
        }
    }

    // ------------------------------------------------------------------ Phi rebalance

    fn emit_phi_rebalance(&mut self) {
        self.line("# --- Phi = 0 maintenance -------------------------------------------");
        self.line("def phi_rebalance(network: VesselNetwork) -> VesselNetwork:");
        self.indent();
        self.line("\"\"\"");
        self.line("Rebalance network until Phi(R) = sum I(V,V) - sum P(V) = 0.");
        self.line("Uses gradient descent on kappa fields.");
        self.line("\"\"\"");
        self.line("for _step in range(MAX_REBALANCE):");
        self.indent();
        // compute Phi approximation: sum of kappa (proxy for I) - sum of boundary (proxy for P)
        let mut phi_parts_num: Vec<String> = Vec::new();
        let mut phi_parts_den: Vec<String> = Vec::new();
        for vd in &self.program.vessels {
            phi_parts_num.push(format!("network.{}_kappa", vd.name));
            phi_parts_den.push(format!("network.{}_boundary", vd.name));
        }
        if phi_parts_num.is_empty() {
            self.line("break  # no vessels");
        } else {
            let num = phi_parts_num.join(" + ");
            let den = phi_parts_den.join(" + ");
            self.line(&format!("phi = ({num}) - ({den})"));
            self.line("if abs(phi) < PHI_TOL:");
            self.indent();
            self.line("break");
            self.dedent();
            self.line("# nudge each vessel kappa toward boundary");
            for vd in &self.program.vessels {
                let n = &vd.name;
                if !vd.sentient {
                    self.line(&format!(
                        "network.{n}_kappa -= 0.01 * phi / {n}",
                        n = n
                    ));
                }
            }
        }
        self.dedent(); // for
        self.line("return network");
        self.dedent(); // fn
        self.line("");
    }

    // ------------------------------------------------------------------ output helpers

    fn line(&mut self, s: &str) {
        let pad = "    ".repeat(self.indent);
        writeln!(self.out, "{pad}{s}").unwrap();
    }

    fn indent(&mut self) { self.indent += 1; }
    fn dedent(&mut self) { if self.indent > 0 { self.indent -= 1; } }
}

// ------------------------------------------------------------------ expression helpers

fn expr_to_python(expr: &Expr) -> String {
    match expr {
        Expr::FloatLit(v)   => format!("{v}"),
        Expr::BoolLit(b)    => if *b { "True".into() } else { "False".into() },
        Expr::Ident(name)   => name.clone(),
        Expr::BinOp { op, left, right } => {
            let l = expr_to_python(left);
            let r = expr_to_python(right);
            let o = match op {
                BinOpKind::Add  => "+",
                BinOpKind::Sub  => "-",
                BinOpKind::Mul  => "*",
                BinOpKind::Div  => "/",
                BinOpKind::Lt   => "<",
                BinOpKind::Gt   => ">",
                BinOpKind::LtEq => "<=",
                BinOpKind::GtEq => ">=",
                BinOpKind::And  => "and",
                BinOpKind::Or   => "or",
            };
            format!("({l} {o} {r})")
        }
        Expr::UnaryOp { op, expr } => {
            let e = expr_to_python(expr);
            match op {
                UnaryOpKind::Neg => format!("(-{e})"),
                UnaryOpKind::Not => format!("(not {e})"),
            }
        }
        Expr::Call { callee, args } => {
            let a: Vec<String> = args.iter().map(expr_to_python).collect();
            format!("{callee}({})", a.join(", "))
        }
        Expr::Member { object, field } => {
            format!("{}.{}", expr_to_python(object), field)
        }
        Expr::Forall { param, body } => {
            format!("all({} for {} in _vessels)", expr_to_python(body), param)
        }
        Expr::If { cond, then, else_ } => {
            format!("({} if {} else {})",
                expr_to_python(then), expr_to_python(cond), expr_to_python(else_))
        }
    }
}

/// Produce a doc-string description of an expression.
fn expr_doc(expr: &Expr) -> String {
    expr_to_python(expr)
}

/// Emit a law body with the forall parameter substituted for a specific vessel name.
fn emit_law_body_for_vessel(body: &Expr, param: &str, vessel: &str) -> String {
    subst_expr(body, param, vessel)
}

fn subst_expr(expr: &Expr, param: &str, value: &str) -> String {
    match expr {
        Expr::Ident(name) if name == param => format!("network.{value}_kappa"),
        Expr::Ident(name) => name.clone(),
        Expr::FloatLit(v) => format!("{v}"),
        Expr::BoolLit(b)  => if *b { "True".into() } else { "False".into() },
        Expr::BinOp { op, left, right } => {
            let l = subst_expr(left, param, value);
            let r = subst_expr(right, param, value);
            let o = match op {
                BinOpKind::Add  => "+", BinOpKind::Sub  => "-",
                BinOpKind::Mul  => "*", BinOpKind::Div  => "/",
                BinOpKind::Lt   => "<", BinOpKind::Gt   => ">",
                BinOpKind::LtEq => "<=", BinOpKind::GtEq => ">=",
                BinOpKind::And  => "and", BinOpKind::Or => "or",
            };
            format!("({l} {o} {r})")
        }
        Expr::UnaryOp { op, expr } => {
            let e = subst_expr(expr, param, value);
            match op {
                UnaryOpKind::Neg => format!("(-{e})"),
                UnaryOpKind::Not => format!("(not {e})"),
            }
        }
        Expr::Call { callee, args } => {
            let a: Vec<String> = args.iter().map(|a| subst_expr(a, param, value)).collect();
            format!("{callee}({})", a.join(", "))
        }
        Expr::Member { object, field } => {
            format!("{}.{}", subst_expr(object, param, value), field)
        }
        Expr::Forall { param: fp, body } => {
            format!("all({} for {} in _vessels)", subst_expr(body, param, value), fp)
        }
        Expr::If { cond, then, else_ } => {
            format!("({} if {} else {})",
                subst_expr(then, param, value),
                subst_expr(cond, param, value),
                subst_expr(else_, param, value))
        }
    }
}

// ------------------------------------------------------------------ LLVM IR stub

/// Stub: future native target via LLVM.
/// Call this in main.rs when `--target llvm` flag is passed.
pub fn emit_llvm_ir_stub(program: &Program) -> String {
    let mut out = String::new();
    writeln!(out, "; Vessel LLVM IR stub — generated by vesselc").unwrap();
    writeln!(out, "; Each vessel becomes a global constant holding its kappa value.").unwrap();
    writeln!(out).unwrap();
    for vd in &program.vessels {
        let kv = match &vd.kappa {
            Expr::FloatLit(v) => *v,
            _ => 0.5,
        };
        writeln!(out, "@{}_kappa = global double {kv:.10}, align 8", vd.name).unwrap();
    }
    writeln!(out).unwrap();
    for fd in &program.fns {
        let params_ir: Vec<String> = fd.params.iter()
            .map(|(p, _)| format!("double %{p}"))
            .collect();
        writeln!(out, "define double @{}({}) {{", fd.name, params_ir.join(", ")).unwrap();
        writeln!(out, "entry:").unwrap();
        writeln!(out, "  ; TODO: translate body").unwrap();
        writeln!(out, "  ret double 0.0").unwrap();
        writeln!(out, "}}").unwrap();
    }
    out
}
